'use client';
import { useMemo, useState } from 'react'; import { ArrowDownToLine, ExternalLink, LoaderCircle, Search, SlidersHorizontal, Sparkles } from 'lucide-react'; import type { Game } from '@/lib/schemas';
const countries = [['tr','Turkey (TR)'],['us','United States (US)'],['gb','United Kingdom (GB)'],['de','Germany (DE)'],['br','Brazil (BR)'],['jp','Japan (JP)']];
const money = (value: number | null, currency: string | null) => value === null ? '—' : value === 0 ? 'Free' : new Intl.NumberFormat(undefined,{style:'currency',currency:currency || 'USD'}).format(value/100);
async function api<T>(path:string, body:unknown):Promise<T>{ const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const json=await res.json(); if(!res.ok) throw new Error(json.error || 'Request failed'); return json; }
export default function Dashboard(){
 const [url,setUrl]=useState('https://store.steampowered.com/category/trains'); const [country,setCountry]=useState('tr'); const [language,setLanguage]=useState('english'); const [maxGames,setMaxGames]=useState(100); const [includeDlc,setIncludeDlc]=useState(false); const [includeFree,setIncludeFree]=useState(true); const [games,setGames]=useState<Game[]>([]); const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [sort,setSort]=useState('reviews');
 const shown=useMemo(()=>games.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='rating'?(b.positivePercent??-1)-(a.positivePercent??-1):sort==='price'?(a.currentPrice??Infinity)-(b.currentPrice??Infinity):sort==='discount'?b.discountPercent-a.discountPercent:b.totalReviews-a.totalReviews),[games,query,sort]);
 async function run(){ setBusy(true);setError('');setGames([]);setProgress(2); try { const d=await api<{games:{appId:number}[]}>('/api/steam/discover',{url,country,language,maxGames}); setProgress(10); const all:Game[]=[]; for(let i=0;i<d.games.length;i+=20){ const ids=d.games.slice(i,i+20).map(x=>x.appId); const e=await api<{games:Game[]}>('/api/steam/enrich',{appIds:ids,country,language,includeDlc,includeFree}); all.push(...e.games);setGames([...all]);setProgress(10+Math.round(((i+ids.length)/d.games.length)*90)); } setProgress(100); } catch(e){setError(e instanceof Error?e.message:'Something went wrong.');} finally{setBusy(false);} }
 function download(kind:'csv'|'json'){ const fields=['name','reviewRating','positivePercent','totalReviews','originalPrice','currentPrice','currency','discountPercent','releaseDate','steamUrl'] as const; const content=kind==='json'?JSON.stringify(shown,null,2):[fields.join(','),...shown.map(g=>fields.map(f=>`"${String(g[f]??'').replaceAll('"','""')}"`).join(','))].join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:kind==='json'?'application/json':'text/csv'}));a.download=`steam-scout.${kind}`;a.click();URL.revokeObjectURL(a.href); }
 return <main className="relative mx-auto min-h-screen max-w-[1500px] px-4 py-8 sm:px-8 lg:py-12">
  <header className="mb-10 flex flex-wrap items-end justify-between gap-6"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-cyan/20 bg-cyan/5 px-3 py-1.5 text-xs font-semibold tracking-wide text-cyan"><Sparkles size={13}/> STEAM DATA, SIMPLIFIED</div><h1 className="text-4xl font-black tracking-[-.04em] sm:text-6xl">Steam <span className="text-cyan">Scout</span></h1><p className="mt-3 max-w-xl text-slate-400">Turn category and sale pages into clean, decision-ready game data.</p></div><div className="hidden text-right text-xs text-slate-500 sm:block"><b className="text-slate-300">Serverless by design</b><br/>No browser sessions. No stored data.</div></header>
  <section className="card mb-6 p-5 sm:p-7"><div className="grid gap-5 lg:grid-cols-[2.5fr_1fr_1fr_.7fr]"><label><span className="label">Steam page URL</span><input className="field" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://store.steampowered.com/sale/..."/></label><label><span className="label">Country</span><select className="field" value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option key={c[0]} value={c[0]}>{c[1]}</option>)}</select></label><label><span className="label">Language</span><select className="field" value={language} onChange={e=>setLanguage(e.target.value)}><option>english</option><option>turkish</option><option>german</option><option>spanish</option><option>japanese</option></select></label><label><span className="label">Max games</span><input className="field" type="number" min="1" max="500" value={maxGames} onChange={e=>setMaxGames(Number(e.target.value))}/></label></div>
   <div className="mt-6 flex flex-wrap items-center gap-x-7 gap-y-4 border-t border-white/10 pt-5">{[[includeDlc,setIncludeDlc,'Include DLC'],[includeFree,setIncludeFree,'Include free games']] .map(([v,set,label])=><label key={label as string} className="flex cursor-pointer items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={v as boolean} onChange={e=>(set as (x:boolean)=>void)(e.target.checked)} className="h-4 w-4 accent-cyan"/>{label as string}</label>)}<button disabled={busy} onClick={run} className="ml-auto flex min-w-40 items-center justify-center gap-2 rounded-xl bg-cyan px-6 py-3 text-sm font-extrabold text-ink transition hover:brightness-110 disabled:opacity-60">{busy?<LoaderCircle className="animate-spin" size={17}/>:<Search size={17}/>} {busy?'Working…':'Fetch games'}</button></div>
   {(busy||progress>0)&&<div className="mt-5"><div className="mb-1 flex justify-between text-[11px] font-bold uppercase tracking-widest text-slate-500"><span>{busy?'Enriching Steam data':'Complete'}</span><span>{progress}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-cyan to-lime transition-all" style={{width:`${progress}%`}}/></div></div>}{error&&<div role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}
  </section>
  <section className="card overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-white/10 p-4"><div className="mr-auto"><span className="font-bold">Results</span><span className="ml-2 rounded-full bg-white/5 px-2 py-1 text-xs text-slate-400">{shown.length} games</span></div><div className="relative"><Search className="absolute left-3 top-3 text-slate-500" size={15}/><input className="field py-2.5 pl-9" placeholder="Filter games" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="relative"><SlidersHorizontal className="absolute left-3 top-3 text-slate-500" size={15}/><select className="field py-2.5 pl-9" value={sort} onChange={e=>setSort(e.target.value)}><option value="reviews">Most reviewed</option><option value="rating">Highest rated</option><option value="discount">Biggest discount</option><option value="price">Lowest price</option></select></div><button disabled={!shown.length} onClick={()=>download('csv')} className="field w-auto py-2.5 disabled:opacity-40"><ArrowDownToLine className="mr-2 inline" size={15}/>CSV</button><button disabled={!shown.length} onClick={()=>download('json')} className="field w-auto py-2.5 disabled:opacity-40"><ArrowDownToLine className="mr-2 inline" size={15}/>JSON</button></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-ink/50 text-[10px] uppercase tracking-widest text-slate-500"><tr>{['Game','Review rating','Positive','Total reviews','Original price','Current price','Discount','Release date','Link'].map(x=><th className="px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y divide-white/5">{shown.map(g=><tr key={g.appId} className="transition hover:bg-white/[.025]"><td className="px-5 py-4 font-semibold">{g.name}<div className="text-xs font-normal text-slate-600">APP {g.appId}</div></td><td className="px-5 py-4 text-slate-300">{g.reviewRating}</td><td className="px-5 py-4"><span className={(g.positivePercent??0)>=80?'text-lime':'text-slate-300'}>{g.positivePercent===null?'—':`${g.positivePercent}%`}</span></td><td className="px-5 py-4 text-slate-400">{g.totalReviews.toLocaleString()}</td><td className="px-5 py-4 text-slate-500 line-through">{money(g.originalPrice,g.currency)}</td><td className="px-5 py-4 font-semibold">{money(g.currentPrice,g.currency)}</td><td className="px-5 py-4">{g.discountPercent?<span className="rounded-md bg-lime/10 px-2 py-1 font-bold text-lime">-{g.discountPercent}%</span>:'—'}</td><td className="px-5 py-4 text-slate-400">{g.releaseDate}</td><td className="px-5 py-4"><a href={g.steamUrl} target="_blank" rel="noreferrer" aria-label={`Open ${g.name} on Steam`} className="text-cyan"><ExternalLink size={17}/></a></td></tr>)}{!shown.length&&!busy&&<tr><td colSpan={9} className="px-5 py-20 text-center"><div className="text-lg font-semibold text-slate-400">Your shortlist starts here</div><div className="mt-1 text-sm text-slate-600">Enter a Steam page above to discover games.</div></td></tr>}</tbody></table></div>
  </section><footer className="py-8 text-center text-xs text-slate-600">Built for research · Data comes directly from Steam · Prices reflect your selected country</footer>
 </main>;
}
